### ISSUE TITLE
Disabled Item Causes Log Error

### ISSUE THREAD

**Issue by milkev** [milkev/Milkevs-Essentials#1]
[19:32:22] [Worker-Main-11/ERROR] (Minecraft) Couldn't load tag trinkets:offhand/charm as it is missing following references: milkevsessentials:flight_charm (from Milkevs Essentials)

dunno how to fix, if anyone does know how let me know or make a pull request.
it doesnt seem to be causing any problems aside from a log error.

**Comment by milkev** [comment]
[19:38:38] [Render thread/ERROR] (Minecraft) Parsing error loading recipe milkevsessentials:flight_charm
 com.google.gson.JsonSyntaxException: Unknown item 'milkevsessentials:flight_charm'
	at net.minecraft.recipe.ShapedRecipe.method_17878(ShapedRecipe.java:253) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.recipe.ShapedRecipe.getItem(ShapedRecipe.java:253) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.recipe.ShapedRecipe.outputFromJson(ShapedRecipe.java:240) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.recipe.ShapedRecipe$Serializer.read(ShapedRecipe.java:273) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.recipe.ShapedRecipe$Serializer.read(ShapedRecipe.java:260) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager.java:123) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager.java:54) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager.java:35) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader.java:13) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload.java:71) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:151) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:125) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:134) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.MinecraftClient.createIntegratedResourceManager(MinecraftClient.java:2152) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1999) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1939) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.start(WorldListWidget.java:437) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.play(WorldListWidget.java:343) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.mouseClicked(WorldListWidget.java:274) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.gui.widget.EntryListWidget.mouseClicked(EntryListWidget.java:359) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:27) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:94) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:490) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:94) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:165) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:165) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165) [minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window.java:310) [minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1137) [minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:728) [minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.52-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]

**Comment by milkev** [comment]
But its not really fixed because i still need to do the trinkets

**Comment by milkev** [comment]
Trinkets slots remain in place, however they are not usable (unless another mod makes use of them) and are not causing any issues on their own.

This may be fixed later but is extremely low priority.

**Comment by milkev** [comment]
dynamic recipe generation no longer works in 1.18, dunno whats wrong with it

**Comment by milkev** [comment]
fixed once again! now its added via a resourcepack via fabric loader i think? idk, either way its working and not making errors so im happy
